GET http://localhost:3000/cart/65f1a1a1a1a1a1a1a1a1a1a1


###POST
POST http://localhost:3000/cart/add
Content-Type: application/json

{
  "userId": "67f1a1a1a1a1a1a1a1a1a1a1",
  "productId": "65f2b2b2b2b2b2b2b2b2b2b2",
  "sellerId": "65f777777777777777777777",
  "price": 9499,
  "quantity": 5
}



###PUT
PUT http://localhost:3000/cart/update
Content-Type: application/json

{
  "userId": "65f1a1a1a1a1a1a1a1a1a1a1",
  "productId": "65f2b2b2b2b2b2b2b2b2b2b2",
  "quantity": 5
}
###DELETE
DELETE http://localhost:3000/cart/remove
Content-Type: application/json

{
  "userId": "67f1a1a1a1a1a1a1a1a1a1a1",
  "productId": "65f2b2b2b2b2b2b2b2b2b2b2"
}
